### ISSUE TITLE
Coupled front-end and back-end?

### ISSUE THREAD

**Issue by fneedly** [gschick3/recinv#3]
Do we want the front-end to call the back-end as an API, or do we want the back-end to serve the pages from its server?

The first option would require a bit more work on the front-end team to grab the right data, but it would allow them to only deal with API endpoints.

The second option would require both teams to work together to properly reference things from the back-end in the front-end code and to create a page controller for UI endpoints, but it would allow the entire project to be run on a single server.

**Comment by josmoo** [comment]
We need one more stretch goal, and good ones to go for imo would either be "create a web API layer for backend interactions", or "options for user if they forgot their username or password".

 which is easier?
 
1. Using the front-end to call the back-end as an API
or 
2. having the back-end serve the pages from its server and implement the forgotten username/password

Or are they about the same and my whole comment was pointless

**Comment by Hailey1005** [comment]
I would go with the second option so we can all chip in our brainpower :)

**Comment by fneedly** [comment]
@josmoo It looks like setting up password forgotten username/password is a fair amount of work. Using the front-end to call the API seems like a much easier thing to do.

**Comment by fneedly** [comment]
@Hailey1005 Josh makes a good point that the first option gets to a stretch goal, which is a nice incentive. I don't believe it will be any harder (may even be easier) than the second option.

**Comment by Hailey1005** [comment]
Well if you said so, I'm open to try either approach. I'm just a little worried about the timeline since the visual part isn't close to being finalized so not sure if that would affect the API integration process.
